#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct ProviderPreset {
    pub(crate) id: &'static str,
    pub(crate) base_url: &'static str,
    pub(crate) api_key_env: Option<&'static str>,
    pub(crate) models_url: Option<&'static str>,
    pub(crate) default_model: Option<&'static str>,
    pub(crate) setup_note: &'static str,
}

pub(crate) const PROVIDER_PRESETS: &[ProviderPreset] = &[
    ProviderPreset {
        id: "groq",
        base_url: "https://api.groq.com/openai/v1",
        api_key_env: Some("GROQ_API_KEY"),
        models_url: None,
        default_model: Some("llama-3.3-70b-versatile"),
        setup_note: "Hosted API. A Groq account/key is required; free developer limits may apply.",
    },
    ProviderPreset {
        id: "openrouter",
        base_url: "https://openrouter.ai/api/v1",
        api_key_env: Some("OPENROUTER_API_KEY"),
        models_url: None,
        default_model: Some("openrouter/free"),
        setup_note:
            "Hosted API. The default free router is zero-price but rate and daily limits apply.",
    },
    ProviderPreset {
        id: "gemini",
        base_url: "https://generativelanguage.googleapis.com/v1beta/openai",
        api_key_env: Some("GEMINI_API_KEY"),
        models_url: None,
        default_model: Some("gemini-2.5-flash"),
        setup_note: "Hosted API. Free-tier availability depends on model, account, and region.",
    },
    ProviderPreset {
        id: "github-models",
        base_url: "https://models.github.ai/inference",
        api_key_env: Some("GITHUB_TOKEN"),
        models_url: Some("https://models.github.ai/catalog/models"),
        default_model: Some("openai/gpt-4.1"),
        setup_note: "Hosted preview API with included rate-limited GitHub account usage.",
    },
    ProviderPreset {
        id: "opencode",
        base_url: "https://opencode.ai/zen/v1",
        api_key_env: Some("OPENCODE_API_KEY"),
        models_url: None,
        default_model: Some("claude-3-7-sonnet"),
        setup_note: "Hosted API. OpenCode Zen AI coding gateway. Key from opencode.ai/auth.",
    },
    ProviderPreset {
        id: "gmicloud",
        base_url: "https://api.gmi-serving.com/v1",
        api_key_env: Some("GMI_CLOUD_API_KEY"),
        models_url: None,
        default_model: Some("deepseek-ai/DeepSeek-V4-Pro"),
        setup_note: "Hosted API. GMI Cloud AI inference platform. Key from console.gmicloud.ai.",
    },
    ProviderPreset {
        id: "nvidia",
        base_url: "https://integrate.api.nvidia.com/v1",
        api_key_env: Some("NVIDIA_API_KEY"),
        models_url: None,
        default_model: Some("meta/llama-3.3-70b-instruct"),
        setup_note: "Hosted API. NVIDIA NIM microservices. An NVIDIA API key is required.",
    },
    ProviderPreset {
        id: "openai",
        base_url: "https://api.openai.com/v1",
        api_key_env: Some("OPENAI_API_KEY"),
        models_url: None,
        default_model: None,
        setup_note: "Hosted paid API. Select a model available to your OpenAI project.",
    },
    ProviderPreset {
        id: "ollama",
        base_url: "http://localhost:11434/v1",
        api_key_env: None,
        models_url: None,
        default_model: Some("llama3.2"),
        setup_note: "Local and no-key by default. Start Ollama and pull a model first.",
    },
    ProviderPreset {
        id: "ollama_cloud",
        base_url: "https://api.ollama.com/v1",
        api_key_env: Some("OLLAMA_API_KEY"),
        models_url: None,
        default_model: Some("llama3.3:70b"),
        setup_note: "Hosted API. Ollama Cloud inference platform. An OLLAMA_API_KEY is required.",
    },
    ProviderPreset {
        id: "lm-studio",
        base_url: "http://localhost:1234/v1",
        api_key_env: None,
        models_url: None,
        default_model: None,
        setup_note: "Local and no-key by default. Start the LM Studio server and load a model.",
    },
];
